package poker.gui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: nickers
 * Date: 2010-09-01
 * Time: 16:21:33
 * To change this template use File | Settings | File Templates.
 */
public class PokerUI {
    private JButton button1;
    private JButton button2;
    private JButton button5;
    private JButton button6;
    private JButton button4;
    private JButton button3;
    private JButton throwDices;
    private JButton finishPart;
    private JToggleButton a1ToggleButton;
    private JToggleButton a3ToggleButton;
    private JToggleButton a5ToggleButton;
    private JToggleButton a4ToggleButton;
    private JToggleButton a2ToggleButton;
    private JPanel mainPanel;

    public PokerUI() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setPreferredSize(new Dimension(500, 300));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1, BorderLayout.NORTH);
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        toolBar1.setRollover(false);
        toolBar1.putClientProperty("JToolBar.isRollover", Boolean.FALSE);
        panel1.add(toolBar1, BorderLayout.CENTER);
        toolBar1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.TOP));
        button1 = new JButton();
        button1.setText("Button");
        button1.setMnemonic('B');
        button1.setDisplayedMnemonicIndex(0);
        toolBar1.add(button1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel2, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setBackground(new Color(-16777216));
        panel3.setEnabled(false);
        panel2.add(panel3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel4.setBackground(new Color(-13408768));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 15;
        gbc.ipady = 15;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel3.add(panel4, gbc);
        panel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-1)), null));
        button2 = new JButton();
        button2.setMaximumSize(new Dimension(50, 50));
        button2.setMinimumSize(new Dimension(50, 50));
        button2.setPreferredSize(new Dimension(50, 50));
        button2.setRolloverEnabled(true);
        button2.setText("K1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;
        panel4.add(button2, gbc);
        button3 = new JButton();
        button3.setMaximumSize(new Dimension(50, 50));
        button3.setMinimumSize(new Dimension(50, 50));
        button3.setOpaque(true);
        button3.setPreferredSize(new Dimension(50, 50));
        button3.setRolloverEnabled(true);
        button3.setText("K2");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(button3, gbc);
        button4 = new JButton();
        button4.setMaximumSize(new Dimension(50, 50));
        button4.setMinimumSize(new Dimension(50, 50));
        button4.setPreferredSize(new Dimension(50, 50));
        button4.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(button4, gbc);
        button5 = new JButton();
        button5.setMaximumSize(new Dimension(50, 50));
        button5.setMinimumSize(new Dimension(50, 50));
        button5.setPreferredSize(new Dimension(50, 50));
        button5.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(button5, gbc);
        button6 = new JButton();
        button6.setMaximumSize(new Dimension(50, 50));
        button6.setMinimumSize(new Dimension(50, 50));
        button6.setPreferredSize(new Dimension(50, 50));
        button6.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(button6, gbc);
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, 26));
        label1.setForeground(new Color(-1));
        label1.setText("TY");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        panel3.add(label1, gbc);
        throwDices = new JButton();
        throwDices.setPreferredSize(new Dimension(75, 50));
        throwDices.setText("Rzut");
        throwDices.setVerticalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        panel3.add(throwDices, gbc);
        finishPart = new JButton();
        finishPart.setPreferredSize(new Dimension(75, 50));
        finishPart.setText(" OK ");
        finishPart.setVerticalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        panel3.add(finishPart, gbc);
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel2.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, 1, 1, null, new Dimension(0, 0), new Dimension(-1, 0), 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        panel5.setBackground(new Color(-16777216));
        panel2.add(panel5, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        panel6.setBackground(new Color(-13408768));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 15;
        gbc.ipady = 15;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel5.add(panel6, gbc);
        panel6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-1)), null));
        a1ToggleButton = new JButton();
        a1ToggleButton.setMaximumSize(new Dimension(50, 50));
        a1ToggleButton.setMinimumSize(new Dimension(50, 50));
        a1ToggleButton.setPreferredSize(new Dimension(50, 50));
        a1ToggleButton.setText("1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(a1ToggleButton, gbc);
        a4ToggleButton = new JButton();
        a4ToggleButton.setMaximumSize(new Dimension(50, 50));
        a4ToggleButton.setMinimumSize(new Dimension(50, 50));
        a4ToggleButton.setPreferredSize(new Dimension(50, 50));
        a4ToggleButton.setText("4");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(a4ToggleButton, gbc);
        a5ToggleButton = new JButton();
        a5ToggleButton.setMaximumSize(new Dimension(50, 50));
        a5ToggleButton.setMinimumSize(new Dimension(50, 50));
        a5ToggleButton.setPreferredSize(new Dimension(50, 50));
        a5ToggleButton.setText("5");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(a5ToggleButton, gbc);
        a3ToggleButton = new JButton();
        a3ToggleButton.setMaximumSize(new Dimension(50, 50));
        a3ToggleButton.setMinimumSize(new Dimension(50, 50));
        a3ToggleButton.setPreferredSize(new Dimension(50, 50));
        a3ToggleButton.setText("3");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(a3ToggleButton, gbc);
        a2ToggleButton = new JButton();
        a2ToggleButton.setMaximumSize(new Dimension(50, 50));
        a2ToggleButton.setMinimumSize(new Dimension(50, 50));
        a2ToggleButton.setPreferredSize(new Dimension(50, 50));
        a2ToggleButton.setText("2");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(a2ToggleButton, gbc);
        final JLabel label2 = new JLabel();
        label2.setFont(new Font(label2.getFont().getName(), Font.BOLD, 26));
        label2.setForeground(new Color(-1));
        label2.setText("Przeciwnik");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel5.add(label2, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
